'use client'
import { Provider } from '@/context/foods'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider>
    <html lang="tr">
      <body>{children}</body>
    </html>
    </Provider>
  )
}
